server:
    port: <%= port  %>

mybatis:
    type-aliases-package: <%= groupCases.splitByDot %>.<%= nameCases.splitByDot %>.model

spring:
    datasource:
        driverClassName:  com.mysql.jdbc.Driver
        url:  jdbc:mysql://localhost:3306/<%= nameCases.splitByDot %>?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username:  root
        password:  root
        type: com.zaxxer.hikari.HikariDataSource
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 300
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 100
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
    level:
        <%= groupCases.splitByDot %>.<%= nameCases.splitByDot %>: DEBUG
