server:
    port: <%= port  %>

mybatis:
    type-aliases-package: <%= groupCases.splitByDot %>.<%= nameCases.splitByDot %>.model

spring:
    datasource:
        driverClassName:  com.mysql.jdbc.Driver
        url:  jdbc:mysql://localhost:3306/<%= nameCases.splitByDot %>?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username:  root
        password:  root

logging:
    level:
        <%= groupCases.splitByDot %>.<%= nameCases.splitByDot %>: DEBUG
